server:
  port: 8080
###配置thymeleaf
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/member?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  thymeleaf:
    cache: false
    suffix: .html
    mode: HTML
    prefix: classpath:/templates/
    servlet:
      content-type: text/html
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java #重启目录
  resources:
    static-locations:  classpath:/templates/,classpath:/resources/,classpath:/static/ #静态资源文件夹路径
mybatis:
  type-aliases-package: com.member.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #添加打印日志信息
mapper:
  mappers: com.member.base.common.mapper.MySqlCommonMapper